name: Ant Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        java: [11, 12, 13, 14, 15, 16]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: java -version && ant -version
    - run: ant clean && ant dist && ant test test.javac6 test.javac8
